/**
 * NR-13 Report Template - Mock Data
 * 
 * Fixture temporária com dados realistas para desenvolvimento do template.
 * Pode ser removida no futuro sem refatoração do layout.
 * 
 * REGRAS:
 * - Não duplicar regras de negócio no mock
 * - Não recalcular engenharia dentro do template
 * - O mock deve poder ser removido sem alterar o layout
 */

import type { TechnicalReport, ReportPhoto } from '../../types';
import type { MeasurementPoint } from '@/modules/engineering/types';
import type { Nr13TemplateData, CompanyInfo } from './types';

export const MOCK_COMPANY: CompanyInfo = {
  name: 'EngeServ Engenharia e Inspeções',
  tagline: 'Inspeção Técnica · NR-13 · ASME · API',
  address: 'Rua das Palmeiras, 1234 – Centro – São Paulo/SP',
  phone: '(11) 3456-7890',
  email: 'contato@engeserv.com.br',
  website: 'www.engeserv.com.br',
  cnpj: '12.345.678/0001-90',
};

const now = new Date();
const inspectionDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000); // 7 days ago

export const MOCK_MEASUREMENTS: MeasurementPoint[] = [
  { id: 'm1', inspectionId: 'insp-001', point: 'P1', thicknessMm: 8.42, angleDeg: 0, notes: 'Ponto frontal - casco', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm2', inspectionId: 'insp-001', point: 'P2', thicknessMm: 8.38, angleDeg: 45, notes: 'Quadrante inferior direito', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm3', inspectionId: 'insp-001', point: 'P3', thicknessMm: 8.51, angleDeg: 90, notes: 'Ponto lateral direito', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm4', inspectionId: 'insp-001', point: 'P4', thicknessMm: 7.89, angleDeg: 135, notes: 'Região de solda longitudinal', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm5', inspectionId: 'insp-001', point: 'P5', thicknessMm: 8.45, angleDeg: 180, notes: 'Ponto traseiro - casco', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm6', inspectionId: 'insp-001', point: 'P6', thicknessMm: 8.32, angleDeg: 225, notes: 'Quadrante inferior esquerdo', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm7', inspectionId: 'insp-001', point: 'P7', thicknessMm: 8.55, angleDeg: 270, notes: 'Ponto lateral esquerdo', createdAt: inspectionDate, updatedAt: inspectionDate },
  { id: 'm8', inspectionId: 'insp-001', point: 'P8', thicknessMm: 7.95, angleDeg: 315, notes: 'Região de solda circunferencial', createdAt: inspectionDate, updatedAt: inspectionDate },
];

export const MOCK_PHOTOS: ReportPhoto[] = [
  { id: 'p1', category: 'VISTA_GERAL', url: '/photos/vista-geral.jpg', caption: 'Vista geral do equipamento', order: 0, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p2', category: 'PLACA', url: '/photos/placa.jpg', caption: 'Placa de identificação do fabricante', order: 1, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p3', category: 'CORROSAO', url: '/photos/corrosao-1.jpg', caption: 'Indícios de corrosão na região inferior', order: 2, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p4', category: 'ULTRASSOM', url: '/photos/ultrassom.jpg', caption: 'Medição por ultrassom - ponto P4', order: 3, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p5', category: 'SOLDA', url: '/photos/solda.jpg', caption: 'Solda longitudinal - inspeção visual', order: 4, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p6', category: 'VALVULA', url: '/photos/valvula.jpg', caption: 'Válvula de segurança - estado geral', order: 5, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p7', category: 'MANOMETRO', url: '/photos/manometro.jpg', caption: 'Manômetro - leitura verificada', order: 6, takenAt: inspectionDate, takenBy: 'insp-001' },
  { id: 'p8', category: 'CORROSAO', url: '/photos/corrosao-2.jpg', caption: 'Corrosão localizada na junta circunferencial', order: 7, takenAt: inspectionDate, takenBy: 'insp-001' },
];

/**
 * Gera um TechnicalReport mock completo para desenvolvimento do template.
 * Use esta função para obter dados de teste realistas.
 */
export function createMockTechnicalReport(): TechnicalReport {
  return {
    id: 'rpt-mock-001',
    identification: {
      reportNumber: `LT-${now.getFullYear()}-00147`,
      version: 1,
      type: 'NR13',
      status: 'DRAFT',
      createdAt: now,
      updatedAt: now,
      inspectionDate: inspectionDate,
      issuedAt: undefined,
      expiresAt: undefined,
      artNumber: 'ART-2024-00582',
      inspectorId: 'usr-insp-001',
      inspectorName: 'Carlos Eduardo Silva',
      engineerId: 'usr-eng-001',
      engineerName: 'Eng. Roberto Almeida',
      managerId: 'usr-mgr-001',
      managerName: 'Eng. Maria Fernanda Costa',
    },
    client: {
      id: 'cli-001',
      name: 'Petroquímica ABC Ltda.',
      cnpj: '12.345.678/0001-90',
      address: 'Rodovia BR-101, Km 45, Industrial',
      city: 'Cubatão',
      state: 'SP',
      contactName: 'João Pereira',
      contactEmail: 'jpereira@petroquimica-abc.com.br',
      contactPhone: '(13) 3456-7890',
      responsibleTechnicalId: 'CREA-123456',
      responsibleTechnicalName: 'Eng. João Pereira',
    },
    equipment: {
      id: 'eq-001',
      tag: 'V-101',
      type: 'VASO_DE_PRESSAO',
      description: 'Vaso de pressão horizontal - Trocador de calor da unidade de destilação',
      manufacturer: 'Construtora Nacional de Equipamentos (CNE)',
      manufactureYear: 2008,
      serialNumber: 'CNE-2008-VP-4521',
      designCode: 'ASME SEC.VIII div.I/2021',
      designPressureBar: 25.0,
      designTemperatureC: 350,
      operatingPressureBar: 18.5,
      operatingTemperatureC: 280,
      mawpBar: 24.8,
      hydroTestPressureBar: 32.5,
      originalThicknessMm: 10.0,
      minThicknessMm: 6.5,
      headType: 'Semielíptico',
      headMaterial: 'SA-516 Gr.70',
      bodyMaterial: 'SA-516 Gr.70',
      headNominalThicknessMm: 12.0,
      volumeLiters: 8500,
      corrosionAllowanceMm: 3.0,
      jointEfficiency: 0.85,
      fluidType: 'Água processada',
      fluidClass: 'D',
      riskGroup: 2,
      nr13Category: 'II',
    },
    executiveSummary: {
      overview: 'Laudo técnico de inspeção NR-13 realizado no vaso de pressão V-101 (Troca do calor da unidade de destilação) da Petroquímica ABC Ltda. O equipamento foi submetido a inspeção visual externa, medições de espessura por ultrassom em 8 pontos do casco, e análise de integridade conforme ASME BPVC VIII-1 e NR-13. A menor espessura encontrada foi de 7.89 mm (Ponto P4), acima da espessura mínima admissível de 6.5 mm. O equipamento apresenta taxa de corrosão controlada e vida útil remanescente adequada.',
      keyFindings: [
        'Menor espessura: 7.89 mm no ponto P4 (região de solda longitudinal)',
        'Espessura mínima admissível: 6.5 mm (margem de 21.4%)',
        'Taxa de corrosão estimada: 0.15 mm/ano',
        'Vida útil remanescente estimada: 9.3 anos',
        'PMTA calculada: 24.8 bar (acima da pressão de operação)',
      ],
      overallStatus: 'ACEITAVEL_COM_RESTRICOES',
      criticalityLevel: 'MEDIUM',
      requiresImmediateAction: false,
    },
    inspectionData: {
      inspection: {
        id: 'insp-001',
        equipmentId: 'eq-001',
        inspectorId: 'usr-insp-001',
        status: 'APROVADA',
        startedAt: inspectionDate,
        completedAt: inspectionDate,
        approvedAt: now,
        type: 'PERIODICA',
        notes: 'Inspeção periódica anual conforme cronograma NR-13',
        recommendations: ['Monitorar região de solda longitudinal (P4)', 'Verificar válvula de segurança próximo ao vencimento'],
      },
      equipment: {
        id: 'eq-001',
        tag: 'V-101',
        type: 'VASO_DE_PRESSAO',
        description: 'Vaso de pressão horizontal - Trocador de calor da unidade de destilação',
        manufacturer: 'Construtora Nacional de Equipamentos (CNE)',
        manufactureYear: 2008,
        serialNumber: 'CNE-2008-VP-4521',
        designCode: 'ASME SEC.VIII div.I/2021',
        designPressureBar: 25.0,
        designTemperatureC: 350,
        operatingPressureBar: 18.5,
        operatingTemperatureC: 280,
        mawpBar: 24.8,
        hydroTestPressureBar: 32.5,
        originalThicknessMm: 10.0,
        minThicknessMm: 6.5,
        headType: 'Semielíptico',
        headMaterial: 'SA-516 Gr.70',
        bodyMaterial: 'SA-516 Gr.70',
        headNominalThicknessMm: 12.0,
        volumeLiters: 8500,
        corrosionAllowanceMm: 3.0,
        jointEfficiency: 0.85,
        fluidType: 'Água processada',
        fluidClass: 'D',
        riskGroup: 2,
        nr13Category: 'II',
      },
      client: {
        id: 'cli-001',
        name: 'Petroquímica ABC Ltda.',
        cnpj: '12.345.678/0001-90',
        address: 'Rodovia BR-101, Km 45, Industrial',
        city: 'Cubatão',
        state: 'SP',
        contactName: 'João Pereira',
        contactEmail: 'jpereira@petroquimica-abc.com.br',
        contactPhone: '(13) 3456-7890',
        responsibleTechnicalId: 'CREA-123456',
        responsibleTechnicalName: 'Eng. João Pereira',
      },
      measurements: MOCK_MEASUREMENTS,
      photos: MOCK_PHOTOS,
      measurementStats: {
        count: 8,
        minThicknessMm: 7.89,
        maxThicknessMm: 8.55,
        avgThicknessMm: 8.31,
        belowMinCount: 0,
        belowMinPercentage: 0,
      },
    },
    engineeringResults: {
      integrityAnalysis: {
        equipmentId: 'eq-001',
        inspectionId: 'insp-001',
        analyzedAt: now,
        analyzedBy: 'usr-eng-001',
        minimumThickness: {
          value: 6.5,
          unit: 'mm',
          status: 'SUCCESS',
          criticality: 'LOW',
          explanation: 'Espessura mínima admissível calculada conforme ASME BPVC VIII-1 para as condições de operação especificadas.',
          normativeReference: 'ASME BPVC VIII-1 UG-27',
          reliability: 'HIGH',
          observations: [],
          metadata: {
            calculationId: 'calc-tmin-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'ASME 2021',
            inputs: { P: 25.0, R: 500, S: 138, E: 0.85 },
            warnings: [],
          },
        },
        corrosionRate: {
          value: 0.15,
          unit: 'mm/ano',
          status: 'SUCCESS',
          criticality: 'LOW',
          explanation: 'Taxa de corrosão estimada com base na diferença entre espessura original e atual, considerando 16 anos de operação.',
          normativeReference: 'API 570 / API 510',
          reliability: 'MEDIUM',
          observations: ['Taxa baseada em medição única; recomenda-se comparar com inspeção anterior'],
          metadata: {
            calculationId: 'calc-cr-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'API 570',
            inputs: { originalThickness: 10.0, currentThickness: 7.89, yearsInService: 16 },
            warnings: ['Dados de inspeção anterior não disponíveis'],
          },
        },
        remainingLife: {
          value: 9.3,
          unit: 'anos',
          status: 'SUCCESS',
          criticality: 'LOW',
          explanation: 'Vida útil remanescente estimada em 9.3 anos até atingir a espessura mínima admissível (6.5 mm).',
          normativeReference: 'API 570 §6.4',
          reliability: 'MEDIUM',
          observations: ['Estimativa baseada na taxa de corrosão atual; condições operacionais podem alterar a vida útil'],
          metadata: {
            calculationId: 'calc-rl-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'API 570',
            inputs: { currentThickness: 7.89, minThickness: 6.5, corrosionRate: 0.15 },
            warnings: [],
          },
        },
        mawp: {
          value: 24.8,
          unit: 'bar',
          status: 'SUCCESS',
          criticality: 'LOW',
          explanation: 'PMTA (Pressão Máxima de Trabalho Admissível) calculada para a menor espessura encontrada, atendendo à pressão de operação.',
          normativeReference: 'ASME BPVC VIII-1 UG-27',
          reliability: 'HIGH',
          observations: [],
          metadata: {
            calculationId: 'calc-mawp-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'ASME 2021',
            inputs: { t: 7.89, R: 500, S: 138, E: 0.85 },
            warnings: [],
          },
        },
        overallStatus: 'ACEITAVEL_COM_RESTRICOES',
        overallCriticality: 'MEDIUM',
        recommendations: [
          'Monitorar a região de solda longitudinal (Ponto P4) com medições semestrais',
          'Programar limpeza interna para melhor avaliação da superfície',
          'Verificar e certificar válvula de segurança antes do próximo ciclo',
        ],
        riskFactors: [
          {
            factor: 'Corrosão localizada na solda longitudinal',
            description: 'Ponto P4 apresenta a menor espessura (7.89 mm), possível início de corrosão localizada na região da solda.',
            severity: 'MEDIUM',
            mitigation: 'Monitoramento semestral por ultrassom',
          },
          {
            factor: 'Tempo de operação (16 anos)',
            description: 'Equipamento com 16 anos de operação; possibilidade de corrosão por pitting em regiões internas não inspecionadas.',
            severity: 'LOW',
            mitigation: 'Inspeção interna na próxima parada programada',
          },
        ],
        formulaVersions: { 'UG-27': 'ASME VIII-1 2021', 'CORROSION_RATE': 'API 570' },
        normativeReferences: ['ASME BPVC VIII-1', 'NR-13', 'API 570', 'API 510'],
      },
      calculations: [
        {
          id: 'calc-tmin-001',
          label: 'Espessura Mínima Admissível',
          value: '6.50',
          unit: 'mm',
          status: 'SUCCESS',
          criticality: 'LOW',
          reliability: 'HIGH',
          explanation: 'Calculada conforme ASME BPVC VIII-1 UG-27 para pressão interna.',
          normativeReference: 'ASME BPVC VIII-1 UG-27',
          observations: [],
          rawValue: 6.5,
          metadata: {
            calculationId: 'calc-tmin-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'ASME 2021',
            inputs: { P: 25.0, R: 500, S: 138, E: 0.85 },
            warnings: [],
          },
        },
        {
          id: 'calc-cr-001',
          label: 'Taxa de Corrosão',
          value: '0.150',
          unit: 'mm/ano',
          status: 'SUCCESS',
          criticality: 'LOW',
          reliability: 'MEDIUM',
          explanation: 'Taxa estimada com base em medição única (sem dados anteriores).',
          normativeReference: 'API 570 §6.4',
          observations: ['Dados de inspeção anterior não disponíveis'],
          rawValue: 0.15,
          metadata: {
            calculationId: 'calc-cr-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'API 570',
            inputs: { originalThickness: 10.0, currentThickness: 7.89, yearsInService: 16 },
            warnings: ['Dados de inspeção anterior não disponíveis'],
          },
        },
        {
          id: 'calc-rl-001',
          label: 'Vida Útil Remanescente',
          value: '9.3',
          unit: 'anos',
          status: 'SUCCESS',
          criticality: 'LOW',
          reliability: 'MEDIUM',
          explanation: 'Até atingir a espessura mínima admissível de 6.5 mm.',
          normativeReference: 'API 570 §6.4',
          observations: [],
          rawValue: 9.3,
          metadata: {
            calculationId: 'calc-rl-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'API 570',
            inputs: { currentThickness: 7.89, minThickness: 6.5, corrosionRate: 0.15 },
            warnings: [],
          },
        },
        {
          id: 'calc-mawp-001',
          label: 'PMTA (Pressão Máx. Trabalho Admissível)',
          value: '24.80',
          unit: 'bar',
          status: 'SUCCESS',
          criticality: 'LOW',
          reliability: 'HIGH',
          explanation: 'Calculada para a menor espessura encontrada (7.89 mm).',
          normativeReference: 'ASME BPVC VIII-1 UG-27',
          observations: [],
          rawValue: 24.8,
          metadata: {
            calculationId: 'calc-mawp-001',
            calculatedAt: now,
            calculatedBy: 'usr-eng-001',
            formulaVersion: '1.0.0',
            normativeVersion: 'ASME 2021',
            inputs: { t: 7.89, R: 500, S: 138, E: 0.85 },
            warnings: [],
          },
        },
      ],
      simulations: [],
      formulaVersions: { 'UG-27': 'ASME VIII-1 2021', 'CORROSION_RATE': 'API 570' },
      normativeReferences: ['ASME BPVC VIII-1', 'NR-13', 'API 570', 'API 510'],
    },
    technicalConclusion: {
      conclusion: 'ACEITAVEL_COM_RESTRICOES',
      justification: 'O equipamento V-101 apresenta integridade compatível com a operação nas condições atuais, com margem de espessura adequada (21.4% acima do mínimo admissível). A taxa de corrosão é controlada (0.15 mm/ano) e a vida útil remanescente estimada é de 9.3 anos. Na região de solda longitudinal (Ponto P4) foi identificada menor espessura (7.89 mm), indicando possível início de corrosão localizada que requer monitoramento.',
      riskFactors: [
        {
          factor: 'Corrosão localizada na solda longitudinal',
          description: 'Ponto P4 com espessura de 7.89 mm (menor valor encontrado)',
          severity: 'MEDIUM',
          mitigation: 'Monitoramento semestral por ultrassom',
        },
        {
          factor: 'Ausência de dados de inspeção anterior',
          description: 'Não foram encontrados registros de inspeções anteriores para comparação de taxa de corrosão',
          severity: 'LOW',
          mitigation: 'Manter registros da inspeção atual como referência para futuras comparações',
        },
      ],
      complianceStatement: 'Este laudo técnico foi elaborado em conformidade com a NR-13 (Norma Regulamentadora nº 13 - Equipamentos de Pressão), ASME Boiler and Pressure Vessel Code Section VIII Division 1 (edição 2021), e normas aplicáveis da API (570/510).',
      restrictions: [
        'Operação com monitoramento reforçado na região da solda longitudinal',
        'Reavaliação em até 12 meses ou antes, conforme evolução da taxa de corrosão',
      ],
    },
    recommendations: {
      immediate: [],
      shortTerm: [
        {
          id: 'rec-st-001',
          description: 'Programar limpeza interna do equipamento para inspeção visual detalhada da superfície e verificação de pitting',
          priority: 'HIGH',
          category: 'INSPECT',
          referencedStandard: 'NR-13 Anexo C',
        },
        {
          id: 'rec-st-002',
          description: 'Verificar e certificar válvula de segurança antes do próximo ciclo de operação',
          priority: 'HIGH',
          category: 'INSPECT',
          referencedStandard: 'NR-13 §13.5',
        },
      ],
      mediumTerm: [
        {
          id: 'rec-mt-001',
          description: 'Implementar monitoramento semestral por ultrassom na região de solda longitudinal (Ponto P4)',
          priority: 'MEDIUM',
          category: 'MONITOR',
          referencedStandard: 'API 570 §6.5',
        },
        {
          id: 'rec-mt-002',
          description: 'Obter registros de inspeções anteriores para cálculo mais preciso da taxa de corrosão',
          priority: 'MEDIUM',
          category: 'DOCUMENT',
        },
      ],
      longTerm: [
        {
          id: 'rec-lt-001',
          description: 'Considerar revestimento interno (liner) na próxima grande manutenção, caso a taxa de corrosão se mantenha ou aumente',
          priority: 'LOW',
          category: 'REPAIR',
        },
      ],
      inspection: {
        nextInspectionDate: new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000),
        intervalMonths: 12,
        type: 'PERIODIC',
        scope: ['Inspeção visual externa e interna', 'Medições de espessura por ultrassom (mínimo 8 pontos)', 'Verificação de válvulas e dispositivos de segurança'],
        criteria: 'Conforme NR-13 e ASME BPVC VIII-1. Aceitar espessura mínima ≥ 6.5 mm.',
      },
    },
    nextInspection: {
      recommendedDate: new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000),
      maxIntervalMonths: 12,
      type: 'PERIODIC',
      justification: 'Intervalo padrão NR-13 para vasos de pressão categoria II, com monitoramento reforçado na região de solda longitudinal',
      scope: ['Inspeção visual externa e interna', 'Medições de espessura por ultrassom', 'Verificação de dispositivos de segurança', 'Análise de integridade'],
      acceptanceCriteria: 'Conforme NR-13 e ASME BPVC VIII-1',
    },
    attachments: {
      photos: MOCK_PHOTOS,
      documents: [],
      calculations: [],
    },
    history: {
      versions: [
        {
          version: 1,
          date: now,
          authorId: 'usr-insp-001',
          authorName: 'Carlos Eduardo Silva',
          authorRole: 'INSPECTOR',
          changes: 'Criação do laudo técnico',
          status: 'DRAFT',
          action: 'CREATED',
        },
      ],
      currentVersion: 1,
      totalVersions: 1,
    },
    validations: [],
    signatures: {
      inspector: {
        id: 'sig-001',
        role: 'INSPECTOR',
        userId: 'usr-insp-001',
        userName: 'Carlos Eduardo Silva',
        userRegistration: 'CREA-SP 123456',
        signedAt: inspectionDate,
        status: 'APPROVED',
      },
      engineer: {
        id: 'sig-002',
        role: 'ENGINEER',
        userId: 'usr-eng-001',
        userName: 'Eng. Roberto Almeida',
        userRegistration: 'CREA-SP 789012',
        signedAt: now,
        status: 'APPROVED',
      },
      manager: {
        id: 'sig-003',
        role: 'MANAGER',
        userId: 'usr-mgr-001',
        userName: 'Eng. Maria Fernanda Costa',
        userRegistration: 'CREA-SP 345678',
        signedAt: now,
        status: 'APPROVED',
      },
      requiredRoles: ['INSPECTOR', 'ENGINEER', 'MANAGER'],
      isComplete: true,
      missingRoles: [],
    },
    metadata: {
      templateId: 'NR13_v2',
      templateVersion: '2.0',
      generatedAt: now,
      generatedBy: 'usr-eng-001',
      lastModifiedBy: 'usr-eng-001',
      lastModifiedAt: now,
      placeholderMode: false,
    },
  };
}

/**
 * Convenience export — TechnicalReport mock pronto para uso no template.
 */
export const MOCK_REPORT = createMockTechnicalReport();

/**
 * Dados completos do template (report + company).
 */
export const MOCK_TEMPLATE_DATA: Nr13TemplateData = {
  report: MOCK_REPORT,
  company: MOCK_COMPANY,
};
